### ISSUE TITLE
Guide on flashing the Arcadia

### ISSUE THREAD

**Issue by mroyme** [EmpWorks/Arcadia#1]
Hey @EmpWorks,

This may not be the appropriate place to communicate regarding this, but since I have no other way to contact you, this will have to do.
 
I have a Corne (CRKBD Rev. 1) with this microcontroller (ordered the kit from Stickeys), and I want some instructions on flashing the firmware.

I did find some [documentation](https://docs.qmk.fm/flashing#raspberry-pi-rp2040-uf2) on the QMK website, but I'm not sure if it's the same pinout. Furthermore, I also have no prior experience with this, so some detailed instructions would be really nice.
If there's any existing video/documentation on the internet that's compatible with the Arcadia, could you point me to them? If not, could you help me out a bit?

For context, I'm trying to change the Corne logo on the display to something cooler, like [this](https://www.reddit.com/r/MechanicalKeyboards/comments/qy6lil/oled_glitch_aesthetic/).

Any help would be really appreciated. Thanks in advance!

**Comment by Error-Code-00x7** [comment]
You will not find any Documentation specifically for the Arcadia. It is a clone of the Splinky mcu and all documentation for splinky applies to Arcadia.

As for the pinouts, QMK converts the pinout assignment depending on the declarations in rules.mk

For Arcadia adding this to the rules.mk will suffice and you wont need to worry about pinout definitions.
CONVERT_TO = rp2040_ce

As for the Logo, you will have to read up on the source and documentation and aply it to your writtem code for the effect to take.

**Comment by dp-codex** [comment]
I have same issue, I used "CONVERT_TO" options but qmk command is waiting with last message  "Waiting for drive to deploy". I recon I need to put board into flash mode. Not sure on how to do it. 
Any help ?

thank you in advance
@mroyme @Error-Code-00x7 @EmpWorks

**Comment by dp-codex** [comment]
> I have same issue, I used "CONVERT_TO" options but qmk command is waiting with last message "Waiting for drive to deploy". I recon I need to put board into flash mode. Not sure on how to do it. Any help ?
> 
> thank you in advance @mroyme @Error-Code-00x7 @EmpWorks

found it
double tap reset button after plugging in usb
